package com.thunder.pay.greendaodb;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.thunder.pay.greendaodb.BankDetail;
import com.thunder.pay.greendaodb.Inventory;

import com.thunder.pay.greendaodb.BankDetailDao;
import com.thunder.pay.greendaodb.InventoryDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig bankDetailDaoConfig;
    private final DaoConfig inventoryDaoConfig;

    private final BankDetailDao bankDetailDao;
    private final InventoryDao inventoryDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        bankDetailDaoConfig = daoConfigMap.get(BankDetailDao.class).clone();
        bankDetailDaoConfig.initIdentityScope(type);

        inventoryDaoConfig = daoConfigMap.get(InventoryDao.class).clone();
        inventoryDaoConfig.initIdentityScope(type);

        bankDetailDao = new BankDetailDao(bankDetailDaoConfig, this);
        inventoryDao = new InventoryDao(inventoryDaoConfig, this);

        registerDao(BankDetail.class, bankDetailDao);
        registerDao(Inventory.class, inventoryDao);
    }
    
    public void clear() {
        bankDetailDaoConfig.clearIdentityScope();
        inventoryDaoConfig.clearIdentityScope();
    }

    public BankDetailDao getBankDetailDao() {
        return bankDetailDao;
    }

    public InventoryDao getInventoryDao() {
        return inventoryDao;
    }

}
